export const GET_POKEMONS = 'GET_POKEMON';
export const GET_POKEMONS_DETAIL = 'GET_POKEMON_DETAIL';
export const SEARCH_POKEMONS = 'SEARCH_POKEMONS'
export const CREATE_NEW_POKEMON = 'CREATE_NEW_POKEMON';
export const FILTER_POKEMONS = 'FILTER_POKEMON';

